---
- hosts: "{{ packages_hosts }}"
  become: yes

  vars_files:
    - "{{ playbook_dir }}/../env.yml"

  tasks:
    - name: "Install basic packages"
      apt:
        name: "{{ basic_packages }}"
        update_cache: yes
        cache_valid_time: 3600
      when: install_basic_packages